### ISSUE TITLE
Thread panic on linux when closing a window

### ISSUE THREAD

**Issue by fasihrana** [fasihrana/skryn#13]
The thread panics with the following error.

```
thread 'WRRenderBackend#0' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', libcore/result.rs:945:5
```

**Comment by fasihrana** [comment]
Curiously this error does not occur in release mode.

**Comment by parasyte** [comment]
This is probably related to primitive event handling. I encounter this panic after fixing the `HoverBegin` and `HoverEnd` handlers on `element::ScrollBox`. See #23

**Comment by fasihrana** [comment]
Fixed by the latest commit
