### ISSUE TITLE
Example "mainexample" unexpectedly quits when entering a non English letter e.g. "é", "à","è"

### ISSUE THREAD

**Issue by LeonGGX** [fasihrana/skryn#29]
Example "mainexample" unexpectedly quits when entering a non English letter e.g. "é", "à","è" when giving a person name, probably due to unproper handling of keyboard.

System : Windows 10
rust version 1.30.1

**Comment by fasihrana** [comment]
Support for international languages is not yet complete. the tracking enhancement is #20

**Comment by fasihrana** [comment]
I think this might now be fixed with the latest commit.

**Comment by LeonGGX** [comment]
It seems to work now, thank you.

**Comment by fasihrana** [comment]
Will close this.

**Comment by fasihrana** [comment]
Further improvements to unicode text handling in unicode_handling branch have now been merged.
