### ISSUE TITLE
Window crashes immediately after opening

### ISSUE THREAD

**Issue by ghost** [fasihrana/skryn#33]
When starting the examples on a freshly installed windows system the window panics while rendering the first frame. The rust panic unwind did not help at all as it only contained the message NotFound without telling me what was missing.

It turned out to be the font FreeMono, as it is used as default font but is missing on a fresh install.

**Comment by fasihrana** [comment]
I'm planning to add a way to load fonts from files to be able to bundle fonts rather than relying on system fonts alone.

**Comment by fasihrana** [comment]
Should be resolved with the last commit.
